name: Build
on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Log Execution
        id: log-execution
        uses: megacorp-actions/log-execution@v1.1.1
        with:
          repository: ${{ github.event.repository.name }}


      - name: Print Results
        run: |
           echo ${{ github.event.repository.name }} "ran at ${{ steps.log-execution.outputs.execution-time }}"

        
